CREATE TABLE `triprecommendation` (
  `id_triprecommendation` SERIAL,
  `id_trip` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(25),
  `google_place_id` VARCHAR(100),
  `lat` DECIMAL(10, 8),
  `lng` DECIMAL(11, 8),
  `long` VARCHAR(100),
  `type` ENUM('P', 'A', 'E') NOT NULL DEFAULT 'P' COMMENT '\'P\'=Place, \'A\'=Activity ,\'E\'=Event',
  `id_activitytype` BIGINT UNSIGNED ,
  `id_eventtype` BIGINT UNSIGNED ,
  `friendfullname` VARCHAR(35) ,
  `isfree` TINYINT NOT NULL DEFAULT 1,
  `cost` DECIMAL(13,2) NOT NULL DEFAULT 0,
  `id_currency` BIGINT UNSIGNED NOT NULL DEFAULT 1,
  `notes` VARCHAR(400) ,
  PRIMARY KEY (`id_triprecommendation`),
  INDEX `triprecommendation_trip_idx` (`id_trip` ASC),
  INDEX `triprecommendation_activitytype_idx` (`id_activitytype` ASC),
  INDEX `triprecommendation_eventtype_idx` (`id_eventtype` ASC),
  INDEX `triprecommendation_currency_idx` (`id_currency` ASC));
